name: Docker Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "First user"
          secondGreeting: "Lukutis"
          thirdGreeting: "This is a third user"